import { db } from "@workspace/db";
import { accommodationsTable, reviewsTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const accommodations = [
  {
    name: "Kigali Serena Hotel",
    type: "hotel" as const,
    description: "A landmark of luxury in Rwanda's capital, the Kigali Serena Hotel offers world-class amenities surrounded by beautifully manicured gardens. With panoramic views of the city and Nyarutarama Lake, this iconic property blends contemporary African design with exceptional hospitality.",
    province: "Kigali City",
    district: "Gasabo",
    address: "KG 609 St, Kigali",
    latitude: -1.9441,
    longitude: 30.0619,
    pricePerNight: "180000",
    currency: "RWF",
    mainImage: "/images/acc-kigali-hotel.png",
    images: ["/images/acc-kigali-hotel.png", "/images/acc-gorilla-lodge.png", "/images/acc-guesthouse.png"],
    amenities: ["WiFi", "Pool", "Restaurant", "Spa", "Gym", "Bar", "Parking", "Airport Shuttle", "Conference Rooms", "Room Service"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.8,
    reviewCount: 312,
    featured: true,
  },
  {
    name: "Marriott Kigali",
    type: "hotel" as const,
    description: "Located in the heart of downtown Kigali, the Marriott offers sophisticated rooms with stunning city views. Experience the perfect blend of modern comfort and vibrant Rwandan culture just steps from the Convention Centre.",
    province: "Kigali City",
    district: "Nyarugenge",
    address: "KN 3 Ave, Kigali CBD",
    latitude: -1.9500,
    longitude: 30.0588,
    pricePerNight: "220000",
    currency: "RWF",
    mainImage: "/images/acc-kigali-apartment.png",
    images: ["/images/acc-kigali-apartment.png", "/images/acc-kigali-hotel.png"],
    amenities: ["WiFi", "Pool", "Restaurant", "Spa", "Gym", "Bar", "Parking", "Rooftop Terrace", "Room Service", "Business Center"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.7,
    reviewCount: 245,
    featured: true,
  },
  {
    name: "Nyungwe Top View Hill Lodge",
    type: "lodge" as const,
    description: "Perched above the ancient Nyungwe rainforest, this exceptional lodge offers breathtaking views over the forest canopy. Wake up to the sounds of chimpanzees and rare birds, and enjoy guided forest walks into one of Africa's oldest and most biodiverse rainforests.",
    province: "Southern Province",
    district: "Nyamasheke",
    address: "Nyungwe National Park Road",
    latitude: -2.4833,
    longitude: 29.1167,
    pricePerNight: "95000",
    currency: "RWF",
    mainImage: "/images/acc-forest-lodge.png",
    images: ["/images/acc-forest-lodge.png", "/images/acc-guesthouse.png"],
    amenities: ["WiFi", "Restaurant", "Bar", "Forest Views", "Guided Tours", "Bird Watching", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.9,
    reviewCount: 87,
    featured: true,
  },
  {
    name: "Lake Kivu Serena Hotel",
    type: "hotel" as const,
    description: "Set on the shores of the magnificent Lake Kivu in Gisenyi, this resort-style hotel combines lake views with lush tropical gardens. Swim in the lake, enjoy water sports, or simply relax on the private beach while soaking in spectacular sunsets.",
    province: "Western Province",
    district: "Rubavu",
    address: "Lake Kivu Shore, Gisenyi",
    latitude: -1.7000,
    longitude: 29.2500,
    pricePerNight: "145000",
    currency: "RWF",
    mainImage: "/images/acc-lake-resort.png",
    images: ["/images/acc-lake-resort.png", "/images/acc-lake-villa.png"],
    amenities: ["WiFi", "Pool", "Lake Beach", "Restaurant", "Bar", "Water Sports", "Spa", "Parking", "Sunset Views"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.6,
    reviewCount: 156,
    featured: true,
  },
  {
    name: "Gorilla's Nest Lodge",
    type: "lodge" as const,
    description: "The ultimate base for gorilla trekking adventures, Gorilla's Nest Lodge sits at the foot of the Virunga volcanoes in Musanze. Rustic luxury meets breathtaking scenery with private cottages, open fireplaces, and guided nature walks through the surrounding forest.",
    province: "Northern Province",
    district: "Musanze",
    address: "Kinigi, Volcanoes National Park",
    latitude: -1.4781,
    longitude: 29.5936,
    pricePerNight: "280000",
    currency: "RWF",
    mainImage: "/images/acc-gorilla-lodge.png",
    images: ["/images/acc-gorilla-lodge.png", "/images/acc-forest-lodge.png"],
    amenities: ["WiFi", "Restaurant", "Bar", "Fireplace", "Gorilla Trekking", "Nature Walks", "Parking", "Mountain Views"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.9,
    reviewCount: 203,
    featured: true,
  },
  {
    name: "The Manor Hotel Kigali",
    type: "hotel" as const,
    description: "A beautifully restored colonial-era manor now transformed into Kigali's most intimate boutique hotel. Set in leafy Nyarutarama with just 14 exclusive rooms, the Manor offers personalized service, a celebrated restaurant, and a peaceful pool surrounded by tropical gardens.",
    province: "Kigali City",
    district: "Gasabo",
    address: "Nyarutarama, KG 9 Ave",
    latitude: -1.9303,
    longitude: 30.0922,
    pricePerNight: "165000",
    currency: "RWF",
    mainImage: "/images/acc-guesthouse.png",
    images: ["/images/acc-guesthouse.png", "/images/acc-kigali-hotel.png"],
    amenities: ["WiFi", "Pool", "Restaurant", "Bar", "Garden", "Parking", "Room Service", "Concierge"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.7,
    reviewCount: 98,
    featured: false,
  },
  {
    name: "Kigali Modern Apartment",
    type: "apartment" as const,
    description: "A sleek, fully-furnished apartment in Kimihurura, Kigali's most sought-after residential neighbourhood. Features a fully equipped kitchen, fast WiFi, and a private balcony with city views. Perfect for extended stays or business travel.",
    province: "Kigali City",
    district: "Gasabo",
    address: "Kimihurura, KG 7 Ave",
    latitude: -1.9559,
    longitude: 30.0789,
    pricePerNight: "55000",
    currency: "RWF",
    mainImage: "/images/acc-kigali-apartment.png",
    images: ["/images/acc-kigali-apartment.png", "/images/acc-kigali-hotel.png"],
    amenities: ["WiFi", "Kitchen", "Washing Machine", "Balcony", "City Views", "Parking", "Security", "Air Conditioning"],
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    averageRating: 4.5,
    reviewCount: 67,
    featured: false,
  },
  {
    name: "Huye Mountain Hotel",
    type: "hotel" as const,
    description: "Nestled in the green hills of Huye (Butare), Rwanda's intellectual and cultural capital, this comfortable hotel is the gateway to the National Museum of Rwanda and nearby tea plantations. Enjoy warm hospitality and stunning mountain scenery.",
    province: "Southern Province",
    district: "Huye",
    address: "Butare Town Center, Huye",
    latitude: -2.5993,
    longitude: 29.7395,
    pricePerNight: "65000",
    currency: "RWF",
    mainImage: "/images/acc-forest-lodge.png",
    images: ["/images/acc-forest-lodge.png"],
    amenities: ["WiFi", "Restaurant", "Bar", "Garden", "Parking", "Conference Room"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.3,
    reviewCount: 54,
    featured: false,
  },
  {
    name: "Akagera Safari Lodge",
    type: "lodge" as const,
    description: "Situated on the shores of Lake Ihema within Akagera National Park, this lodge offers an authentic safari experience in the heart of Rwanda. Fall asleep to hippo calls and wake up to elephants at the water's edge.",
    province: "Eastern Province",
    district: "Kayonza",
    address: "Akagera National Park, Lake Ihema",
    latitude: -1.9000,
    longitude: 30.7500,
    pricePerNight: "195000",
    currency: "RWF",
    mainImage: "/images/acc-safari-lodge.png",
    images: ["/images/acc-safari-lodge.png", "/images/acc-gorilla-lodge.png"],
    amenities: ["WiFi", "Restaurant", "Bar", "Pool", "Game Drives", "Boat Safaris", "Nature Walks", "Parking"],
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.8,
    reviewCount: 134,
    featured: true,
  },
  {
    name: "Kigali Backpackers Hostel",
    type: "hostel" as const,
    description: "The most popular hostel in Kigali, loved by budget travellers and backpackers from around the world. Vibrant social atmosphere, great communal kitchen, lively bar, and knowledgeable staff who can help plan your Rwanda adventure.",
    province: "Kigali City",
    district: "Kicukiro",
    address: "KK 15 Ave, Kicukiro",
    latitude: -1.9767,
    longitude: 30.0649,
    pricePerNight: "15000",
    currency: "RWF",
    mainImage: "/images/acc-guesthouse.png",
    images: ["/images/acc-guesthouse.png"],
    amenities: ["WiFi", "Kitchen", "Bar", "Lockers", "Common Room", "Tour Desk", "Laundry"],
    maxGuests: 1,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.4,
    reviewCount: 289,
    featured: false,
  },
  {
    name: "Musanze Guesthouse & B&B",
    type: "guesthouse" as const,
    description: "A charming family-run guesthouse in the heart of Musanze (Ruhengeri), perfect for gorilla trekking preparation. Enjoy home-cooked Rwandan meals, warm hospitality, and panoramic views of the Virunga volcanoes from the garden.",
    province: "Northern Province",
    district: "Musanze",
    address: "Ruhengeri Town, Musanze",
    latitude: -1.4997,
    longitude: 29.6348,
    pricePerNight: "35000",
    currency: "RWF",
    mainImage: "/images/acc-guesthouse.png",
    images: ["/images/acc-guesthouse.png", "/images/acc-forest-lodge.png"],
    amenities: ["WiFi", "Breakfast Included", "Garden", "Volcano Views", "Tour Desk", "Parking"],
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    averageRating: 4.6,
    reviewCount: 112,
    featured: false,
  },
  {
    name: "Rubavu Lakeside Villa",
    type: "villa" as const,
    description: "An exclusive private villa on the shores of Lake Kivu near Rubavu, perfect for groups and families. Features a private garden extending to the lake, a full kitchen, multiple terraces, and a private dock for swimming and kayaking.",
    province: "Western Province",
    district: "Rubavu",
    address: "Gisenyi Beach Road, Rubavu",
    latitude: -1.6880,
    longitude: 29.2580,
    pricePerNight: "320000",
    currency: "RWF",
    mainImage: "/images/acc-lake-villa.png",
    images: ["/images/acc-lake-villa.png", "/images/acc-lake-resort.png"],
    amenities: ["WiFi", "Private Kitchen", "Lake Access", "Private Dock", "Garden", "BBQ", "Parking", "Kayaks"],
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 2,
    averageRating: 4.9,
    reviewCount: 45,
    featured: true,
  },
];

const reviewData = [
  {
    guestName: "Sarah M.",
    rating: 5,
    title: "Absolutely stunning experience",
    comment: "The Kigali Serena exceeded all my expectations. Impeccable service, beautiful rooms, and the gardens are gorgeous. Will definitely return!",
    stayDate: "2025-11",
  },
  {
    guestName: "James K.",
    rating: 5,
    title: "Best stay in Africa",
    comment: "Coming from Nairobi, I was impressed by how world-class this hotel is. The pool area is spectacular and the food was exceptional.",
    stayDate: "2025-12",
  },
  {
    guestName: "Anna L.",
    rating: 4,
    title: "Great location and service",
    comment: "Excellent hotel in a prime Kigali location. Staff were wonderfully helpful with recommendations. Only minor quibble is the WiFi could be faster.",
    stayDate: "2026-01",
  },
  {
    guestName: "David O.",
    rating: 5,
    title: "Mountain magic",
    comment: "Waking up to the volcano views from Gorilla's Nest was simply magical. Easily the most memorable accommodation I've ever stayed in.",
    stayDate: "2025-10",
  },
  {
    guestName: "Elena R.",
    rating: 5,
    title: "Perfect for gorilla trekking",
    comment: "The lodge staff arranged everything perfectly. After trekking, returning to this beautiful property felt like pure luxury. Worth every franc.",
    stayDate: "2026-01",
  },
];

async function seed() {
  console.log("Seeding database...");

  await db.delete(reviewsTable);
  await db.delete(accommodationsTable);

  const inserted = await db.insert(accommodationsTable).values(accommodations).returning();
  console.log(`Inserted ${inserted.length} accommodations`);

  const reviewInserts = [];
  for (let i = 0; i < inserted.length; i++) {
    const acc = inserted[i];
    const numReviews = Math.min(3, reviewData.length);
    for (let j = 0; j < numReviews; j++) {
      reviewInserts.push({
        accommodationId: acc.id,
        ...reviewData[(i + j) % reviewData.length],
      });
    }
  }

  await db.insert(reviewsTable).values(reviewInserts);
  console.log(`Inserted ${reviewInserts.length} reviews`);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
